version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Inventory-Management"
s3_bucket = "simple-inv"
s3_prefix = "BackEnd"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
