AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Inv-Back

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Inventory-Managment
    Description: INV Managment
    Author: Amol Bohora
    SpdxLicenseId: UNLICENSED
    ReadmeUrl: README.md
    Labels: [ 'Inventory', 'Management' ]
    SemanticVersion: 0.1.0

Globals:
  Function:
    Timeout: 3
    MemorySize: 400

Resources:

  InventoryAPI:
     Type: AWS::Serverless::HttpApi
     Properties:
       Description: Serverless Inventory API
       StageName: Prod
       Domain:
          DomainName: "inv.amolbohora.com"
          CertificateArn: arn:aws:acm:ap-south-1:404907247506:certificate/f5cf49db-493e-495e-816b-eb57f4e49ad5
       CorsConfiguration:
          AllowHeaders:
            - "Content-type"
          AllowOrigins:
            - "*"
          AllowMethods:
            - "POST"
            - "OPTIONS"

  invLive:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: invLive/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: Fuction to see live Inventory
      Policies:
        AmazonDynamoDBFullAccess
      Events:
        invLive:
          Type: HttpApi
          Properties:
            Path: /invLive
            Method: post
            ApiId:
              Ref: InventoryAPI

  export:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: export/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: Fuction to export annual data
      Policies:
       - AmazonDynamoDBFullAccess
       - arn:aws:iam::404907247506:policy/Annual-Export-S3-Lambda-Policy
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:ap-south-1:404907247506:Exporter

  exporter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: exportCaller/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: Fuction to get autocopmlete data
      Policies:
        - arn:aws:iam::404907247506:policy/Export-Sns-Caller
      Events:
        invLive:
          Type: HttpApi
          Properties:
            Path: /export
            Method: post
            ApiId:
              Ref: InventoryAPI

  autocomplete:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: autocomplete/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: Fuction to get autocopmlete data
      Policies:
      - AmazonDynamoDBFullAccess
      - arn:aws:iam::404907247506:policy/AutocompleteS3
      Events:
        invLive:
          Type: HttpApi
          Properties:
            Path: /auto
            Method: post
            ApiId:
              Ref: InventoryAPI



  dataView:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dataView/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: Genral Function for data viewing
      Policies:
        AmazonDynamoDBFullAccess
      Events:
        dataView:
          Type: HttpApi
          Properties:
            Path: /dataView
            Method: post
            ApiId:
              Ref: InventoryAPI


  dataIn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dataIn/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: General Function to get Data In
      Policies:
        AmazonDynamoDBFullAccess
      Events:
        dataIn:
          Type: HttpApi
          Properties:
            Path: /dataIn
            Method: post
            ApiId:
              Ref: InventoryAPI



  authCheck:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: authCheck/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: Signup and Login Function
      Policies:
        AmazonDynamoDBFullAccess
      Events:
        authCheck:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth
            Method: post
            ApiId:
              Ref: InventoryAPI



